name: Request Game
description: Request a new game to add to the list
title: 'Request <Game Name Here>'
labels: ['new-game', 'status-change']
body:
  - type: input
    id: game
    attributes:
      label: Game Title
      placeholder: ex. Team Fortress 2
    validations:
      required: true
  - type: input
    id: game-url
    attributes:
      label: Game Website
      description: A valid hyperlink to the game's website.
      placeholder: ex. https://teamfortress.com
    validations:
      required: false
  - type: dropdown
    id: anti-cheat
    attributes:
      label: Anti-Cheat Software
      description: Which anti-cheat software is the game running?
      options:
        - Easy Anti-Cheat
        - BattlEye
        - XIGNCODE3
        - nProtect GameGuard
        - EQU8
        - VAC
        - Other
    validations:
      required: true
  - type: dropdown
    id: anti-cheat-status
    attributes:
      label: Status of the Anti-Cheat
      description: What is the state of the game? (For more in depth definitions see "Legend" on https://areweanticheatyet.com)
      options:
        - 🚫 Denied
        - 😥 Broken
        - 🕧 Planned
        - 👍 Running
        - ⭐ Supported
    validations:
      required: true
  - type: textarea
    id: tinkering-steps
    attributes:
      label: Tinkering Steps
      description: In case tinkering is required please describe the steps here.
      placeholder: ex. use steam flatpak
    validations:
      required: false
  - type: input
    id: anti-cheat-comment
    attributes:
      label: Proof of Mention
      description: A reputable source that supports your claim of the games status.
      placeholder: ex. https://www.theverge.com/2021/10/5/22709918/valve-steam-deck-supported-games-anti-cheat-proton-eac-battleye-epic
    validations:
      required: true
