on:
  push:
    branches: [master]
    paths:
      - '*'
  workflow_dispatch:

name: Deploy to Github-Pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: false

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v3.0.2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📩 Setup System Dependencies
        run: 'pacman --noconfirm -Syu imagemagick graphicsmagick yarn npm nodejs'

      - name: 🤖 Setup Project
        run: 'yarn'

      - name: 👷 Build
        run: 'yarn export'

      - name: 🎉 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true
