on:
  push:
    branches: [master]
    paths:
      - '*'
  workflow_dispatch:

name: Deploy to Github-Pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v3.0.2
        with:
          path: current

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📩 Setup System Dependencies
        run: 'sudo apt-get update && sudo apt-get install imagemagick && sudo apt-get install graphicsmagick'

      - name: 🤖 Setup Project
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: 👷 Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

      - name: 🎉 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
