on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '**.ts'
      - '**.tsx'
      - 'yarn.lock'
      - 'games.json'
      - 'package.json'

name: Deploy to Github-Pages
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v3.3.0

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}

      - name: 🤖 Setup Project
        run: 'yarn'

      - name: 🌐 Fetch
        run: 'yarn fetch'

      - name: 👷 Build
        run: 'STEAMGRIDDB_KEY=${{ secrets.STEAMGRIDDB_KEY }} PAGES=1 yarn build && yarn export'

      - name: 🎉 Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true
          